#!/usr/bin/exec-suid --real -- /usr/bin/python -I
import sys
sys.path.append('/challenge')

def print_flag():
	try:
		with open("/flag", "r") as f:
			print(f.read())
	except FileNotFoundError:
		print("Error: Flag file not found.")

# Add your imports and other code below here
from paceCParser.parser import RED_TEXT_CODE, RESET_TEXT_CODE, GREEN_TEXT_CODE, parse_file, verify_initial_checks, retrieve_function_body
import os
import re

def check_c_file(current_dir, filename):
    filepath = os.path.join(current_dir, filename)
    if not os.path.isfile(filepath):
        return False, "Unable to find C file named {}. Did you name it something else?".format(filename)

    return True, ""

def check_libraries(file_contents):
    if '#include <stdio.h>' not in file_contents:
        return False, "Missing 'stdio.h' library."

    return True, ""

def check_variables(function_contents):
    variables = [v for v in function_contents if not isinstance(v, str)]

    if len(variables) != 1:
        return False, "Incorrect number of variables."

    for variable in variables:
        if variable.data_type not in ["int", "char", "float"]:
            return False, "{} variable is not of an expected data type, got {} expecting one of int, float, char.".format(variable.name, variable.data_type)

        if variable.data_type == "int" and variable.name != "age":
            return False, "{} variable does not have expected name 'age'.".format(variable.name)

    return True, ""

def check_statements(function_contents):
    print_statements = [s for s in function_contents if isinstance(s, str) and "printf" in s]
    scan_statements = [s for s in function_contents if isinstance(s, str) and "scanf" in s]

    if len(print_statements) != 2:
        return False, "Invalid number of print statements."

    if len(scan_statements) != 1:
        return False, "Invalid number of scanf statements."


    expected_print_statements = [
        'printf("What is your age: ");',
        f'printf("Your age is: %d\\n", age);'
    ]

    for statement in print_statements:
        if statement not in expected_print_statements:
            return False, "Print Statement: {}, does not match expected.".format(statement)

    for statement in scan_statements:
        if statement != f'scanf("%d", &age);':
            return False, "Scanf Statement: {}, does not match expected.".format(statement)

    return True, ""

if __name__ == '__main__':
    current_dir = os.getcwd()

    filename = sys.argv[1]

    passed, error_msg = check_c_file(current_dir, filename)
    if not passed:
        print(f'{RED_TEXT_CODE}Incorrect{RESET_TEXT_CODE}: {error_msg}')
        sys.exit(1)

    filepath = os.path.join(current_dir, filename)
    if not verify_initial_checks(filepath):
        sys.exit(1)

    file_contents = parse_file(filepath)
    main_function = {'function_name': 'main', 'return_type': 'int', 'parameters': []}
    main_function_contents = retrieve_function_body(file_contents, **main_function)

    verification_funcs = [
        check_libraries(file_contents),
        check_variables(main_function_contents),
        check_statements(main_function_contents),
    ]

    for func in verification_funcs:
        passed, error = func
        if not passed:
            print(f'{RED_TEXT_CODE}Incorrect{RESET_TEXT_CODE}: {error}')
            sys.exit(1)

    print(f'{GREEN_TEXT_CODE}Correct{RESET_TEXT_CODE}')
    print("Congragulations! You have passed this challenge! here is your flag:")
    print_flag()
